# Generated by Django 2.2.4 on 2019-09-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Director')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nacion', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nacionalidad')),
                ('foto', models.URLField(verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Director')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nacion', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('anno', models.DateField(blank=True, null=True, verbose_name='Año')),
                ('genero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Género')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elementos.Actor')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elementos.Director')),
            ],
        ),
    ]
