# Generated by Django 2.2.4 on 2019-09-26 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='tituloAlt',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='a.k.a'),
            preserve_default=False,
        ),
    ]
