# Generated by Django 2.2.4 on 2019-09-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0002_pelicula_tituloalt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Actor'),
        ),
    ]
