# Generated by Django 2.2.4 on 2019-09-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0003_auto_20190926_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='anno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
