# Generated by Django 2.2.4 on 2019-09-26 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0005_auto_20190926_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='actor',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elementos.Actor'),
        ),
    ]
