# Generated by Django 2.2.4 on 2019-09-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0007_auto_20190926_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peli_Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementos.Actor')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementos.Pelicula')),
            ],
        ),
    ]
