# Generated by Django 2.2.4 on 2019-09-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0009_auto_20190926_0625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peli_Actor',
        ),
    ]
