# Generated by Django 2.2.4 on 2019-10-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0010_delete_peli_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='anno',
            field=models.PositiveIntegerField(blank=True, default=1888, null=True, verbose_name='Año'),
        ),
    ]
