# Generated by Django 2.2.4 on 2019-10-11 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0011_auto_20191011_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='anno',
            field=models.PositiveIntegerField(blank=True, default=1888, null=True, validators=[django.core.validators.MinValueValidator(1888)], verbose_name='Año'),
        ),
    ]
