# Generated by Django 2.2.4 on 2019-12-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0012_auto_20191011_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cover',
            field=models.URLField(default='www.google.cl', verbose_name='Portada'),
            preserve_default=False,
        ),
    ]
